---
name: 'Twilio Fax'
author: Yevhen Fabizhevskyi
description: 'This GitHub action sends fax with the defined text.'
branding:
  icon: file-text
  color: white
inputs:
  twilio_account_sid:
    description: 'Twilio Account SID.'
    required: true
  twilio_auth_token:
    description: 'Twilio Auth token.'
    required: true
  url:
    description: 'Url to the file that will be send by fax.'
    required: true
  from:
    description: 'Fax sender number (Twilio).'
    required: true
  to:
    description: 'Fax recipient number.'
    required: true
outputs:
  sid:
    description: 'SID of fax operation.'
runs:
  using: 'node16'
  main: 'dist/index.js'
