---
name: Lint

on:
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'bump/patch-**'

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Run Lint
        uses: github/super-linter@v3.14.3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
